name: Unit tests
on: [push, pull_request]

jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install gcc-multilib gdb
          pip3 install -U pip setuptools
          pip3 install -v .[test]

      - name: Compile test programs
        run: |
          cd tests
          make all

      - name: Run x86-32 tests
        run: |
          cd tests
          gdb test_program_32 -x run_tests.py

      - name: Run x86-64 tests
        run: |
          cd tests
          gdb test_program_64 -x run_tests.py
